version: '3.8'

services:
  crud-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_db
    command: -c 'max_connections=300'
    volumes:
      - crud_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
      

  crud:
    build: 
      context: .
      dockerfile: ./CRUD.API/Dockerfile
    depends_on:
      crud-db:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Host=crud-db;Database=crud_db;Username=user;Password=password;Pooling=true;MinPoolSize=0;MaxPoolSize=70;
      - ASPNETCORE_URLS=http://*:80
      - AllowedHosts=*
    ports:
      - "5010:80"
      

  crudtests:
    build: 
      context: .
      dockerfile: ./CRUD.Tests/Dockerfile
    depends_on:
      - crud
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - ConnectionStrings__DefaultConnection=Host=crud-db;Database=crud_db;Username=user;Password=password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: passwd
      #PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON_FILE: '/pgadmin-servers.json'
    ports:
      - "8090:80"
    depends_on:
      - crud-db
    volumes:
      - ./pgadmin/pgadmin-servers.json:/pgadmin-servers.json
      - pgadmin-data:/var/lib/pgadmin
      

volumes:
  crud_db_data:
  pgadmin-data: