// <auto-generated />
using System;
using CRUD.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRUD.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRUD.BLL.Models.Foos.Foo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FooFooId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FooFooId");

                    b.ToTable("Foos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6140), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 1"
                        },
                        new
                        {
                            Id = -2L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6940), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 2"
                        },
                        new
                        {
                            Id = -3L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6947), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 3"
                        },
                        new
                        {
                            Id = -4L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6948), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 4"
                        },
                        new
                        {
                            Id = -5L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6990), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 5"
                        },
                        new
                        {
                            Id = -6L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6991), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 6"
                        },
                        new
                        {
                            Id = -7L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6992), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 7"
                        },
                        new
                        {
                            Id = -8L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6994), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 8"
                        },
                        new
                        {
                            Id = -9L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6995), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 9"
                        },
                        new
                        {
                            Id = -10L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6996), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 10"
                        },
                        new
                        {
                            Id = -11L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(6999), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 11"
                        },
                        new
                        {
                            Id = -12L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7000), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 12"
                        },
                        new
                        {
                            Id = -13L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7001), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 13"
                        },
                        new
                        {
                            Id = -14L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7002), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 14"
                        },
                        new
                        {
                            Id = -15L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7003), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 15"
                        },
                        new
                        {
                            Id = -16L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7004), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 16"
                        },
                        new
                        {
                            Id = -17L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7005), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 17"
                        },
                        new
                        {
                            Id = -18L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7006), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 18"
                        },
                        new
                        {
                            Id = -19L,
                            FooFooId = 1L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7007), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 19"
                        },
                        new
                        {
                            Id = -20L,
                            FooFooId = 2L,
                            IsDeleted = false,
                            LastModifiedDate = new DateTimeOffset(new DateTime(2025, 9, 26, 12, 41, 53, 158, DateTimeKind.Unspecified).AddTicks(7008), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Foo 20"
                        });
                });

            modelBuilder.Entity("CRUD.BLL.Models.Foos.FooFoo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FooFoos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Value = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Value = 2L
                        });
                });

            modelBuilder.Entity("CRUD.BLL.Models.Foos.Foo", b =>
                {
                    b.HasOne("CRUD.BLL.Models.Foos.FooFoo", "FooFoo")
                        .WithMany()
                        .HasForeignKey("FooFooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FooFoo");
                });
#pragma warning restore 612, 618
        }
    }
}
